### ISSUE TITLE
Numpy memory error

### ISSUE THREAD

**Issue by benjaminh** [jeffgreenca/laughr#1]
Hi,
First of all, many thanks for sharing your work, this is exactly what I was looking for !

I wanted to use your program to mute laughs from a TV show (TBBT) just for curiosity ;)
So I followed your instructions:
- extract the audio track from a single 20 minutes episode using `ffmpeg -i input.mp4 output.wav`
- mute laughs using your pre-trained model `python laughr.py --model ../assets/trained-model.h5 --mute-laughs output.wav temp-output.wav`

First, it silently failed with only a "Process stopped" with no output.
I did some investigation and it appears that I have a Memory Error at the end of the `_split_features_into_windows` method. Line 59 : `return np.array(windows)`

After further investigation on the size of `windows` array, here are some figures:
- my `windows` is composed of 3419280 elements
- each element is itself a numpy ndarray of about 300 float64 elements for a total size of 2368 bytes
- so the total size of the `windows` seems to be 8GB

I have only 8GB of RAM on my machine. Do you have any hint to overcome this problem (I heard about the sparse matrices) ? Did you ever encountered this limitation during your own tests ?

**Comment by jeffg-dev** [comment]
I think sparse array/matrix will not help, because the 3419280x30x296 or so (windows x steps x features) is mostly filled with values, sparse helps when most of the values are 0.

The "easiest" solution would be to split your output.wav into smaller parts, for example:
```
ffmpeg -ss 0 -t 10:00 -i input.mp4 -o output1.wav
ffmpeg -ss 10:00 -t 10:00 -i input.mp4 -o output2.wav
```

A "better" solution would be adding a chunking mechanism that takes the input file in parts, runs it through the model for classification, saves the classifications but discards the computed feature array.  

The chunking could probably be added after RawClip uses soundfile to get the raw sound file data, and before extract features.

In my env, 32GB RAM so didn't run into this.  The librosa feature functions did take considerable memory, hence why there is code to chunk that part into smaller pieces for long input.

**Comment by benjaminh** [comment]
Yeah, in the meantime, I checked the sparsity of the matrix and came to the same conclusion.
Indeed, splitting the input audio track solves the problem.

Also, I can see that the numpy array type is float64. I was wondering if using float16 instead would have some downsides (this allowed me to store the array in memory without having to split the input file).
