### ISSUE TITLE
Argument path to training dataset

### ISSUE THREAD

**Issue by benjaminh** [jeffgreenca/laughr#2]
Help says that `laughr.py` should have a `--train` option when training that takes two parameters : `/path/to/L*.wav` and `/path/to/D*.wav`.

Maybe you should specify that those paths should be inside quotes, otherwise it raises an error :
`laughr.py: error: unrecognized arguments: ` followed by the list of files found.

So the command should be `pipenv run python laughr.py --model my_new_model.h5 --train './training/l*.wav' './training/d*.wav'`

This may be obvious but it took me some time to figure it out.

**Comment by jeffg-dev** [comment]
PR is welcome, to update the docs or to solve the problem.

If you didn't figure this out already, it's because your [shell expands `*` ](http://tldp.org/LDP/abs/html/globbingref.html) to the list of files, but not on all platforms.

Another option would be create `--train-laughs` and `--train-not-laughs` params in argparse that allow multiple values, and handle those as `list` of filenames rather than `glob()` in the code.

**Comment by benjaminh** [comment]
I'm not familiar with PRs (followed [this page](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/) for some guidance) because I'm a beginner in contributing, so tell me if I'm doing it the wrong way.

**Comment by jeffg-dev** [comment]
Good job!
